### ISSUE TITLE
cgo调用c代码时，如果C崩溃了，能否在golang里面捕获住，而不让整个进程崩溃呐？

### ISSUE THREAD

**Issue by LiuQIu7** [fananchong/test_cgo_coredump#2]
上次close issue的回答是会误导别人的，cgo crash，只能捕获，而不能让整个进程不崩溃

**Comment by LiuQIu7** [comment]
补充：用的是golang 1.17的版本

**Comment by fananchong** [comment]
见 main3.go 

https://github.com/fananchong/test_cgo_coredump#%E6%8D%95%E8%8E%B7-c-%E9%94%99%E8%AF%AF%E5%B9%B6%E4%B8%94%E4%B8%8D%E9%80%80%E5%87%BA

**Comment by LiuQIu7** [comment]
main3.go用signal函数对SIGSEGV做了信号处理，在信号处理函数中，做了siglongjmp来保证程序不退出。但这样有一个副作用，当在cgo里面对SIGSEGV信号做了自己的信号处理函数，一旦golang的代码调用了cgo的这段代码后，后续的golang代码如果发生了空指针访问发生panic将无法recover，因为SIGSEGV被自己的信息处理函数处理了，golang层就无法处理了，这样代码运行会发生不可预知的问题 @fananchong
